# Generated by Django 4.2.6 on 2023-10-23 19:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_flash_card'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flash_card',
            new_name='FlashCard',
        ),
    ]
